workstation/g810-colorscheme: Implement locking.
The g810-led program seems to cause some ruckus with the device. It's
almost like Linux sees the device being re-plugged in every time
g810-led runs. That also impacts udev.

With some locking here we can keep the script from running
unnecessarily.

diff --git a/workstation/g810-colorscheme b/workstation/g810-colorscheme
--- a/workstation/g810-colorscheme
+++ b/workstation/g810-colorscheme
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+lockfile='/var/run/lock/subsys/g810-colorscheme'
 g810_led='/opt/local/bin/g810-led'
 
 blue='000066'
@@ -13,6 +14,11 @@ purple='8d00a6'
 red='660000'
 white='ffffff'
 yellow='999900'
+
+if ! mkdir "$lockfile" >/dev/null 2>&1; then
+    echo "Could not acquire lock at $lockfile" >&2
+    exit 1
+fi
 
 # Set default key color to light grey.
 $g810_led -an "$gray"
@@ -52,3 +58,6 @@ $g810_led -kn game "$white"
 $g810_led -kn enter "$blue"
 
 $g810_led -c
+
+sleep 10
+rm -rf "$lockfile"
